name: Build and Release Game

on:
  release:
    types: [published]

env:
  ITCH_GAME: ${{ vars.ITCH_GAME }}
  ITCH_USER: ${{ vars.ITCH_USER }}
  STEAM_APP_ID: ${{ vars.STEAM_APP_ID }}

jobs:
  build_game:
    name: Build Game
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        uses: The-Water-Museum/godot-build@v1.0
        with: 
          version: ${{ github.event.release.tag_name }}

  release_itchio:
      name: Upload Game to Itch.io
      runs-on: ubuntu-latest
      needs: [build_game]
      steps:
        - name: Release Game
          uses: The-Water-Museum/release-game/itch@v1.0
          with:
            itch-game: ${{ env.ITCH_GAME }}
            itch-user: ${{ env.ITCH_USER }}
            itch-api-key: ${{ secrets.ITCH_API_KEY }}
            version: ${{ github.event.release.tag_name }}

  release_steam:
      name: Upload Game to Steam
      runs-on: ubuntu-latest
      needs: [build_game]
      steps:
        - name: Release Game
          uses: The-Water-Museum/release-game/steam@v1.0
          with:
            steam-totp-shared-secret: ${{ secrets.STEAM_SHARED_SECRET }}
            steam-username: ${{ secrets.STEAM_USERNAME }}
            steam-password: ${{ secrets.STEAM_PASSWORD }}
            steam-appid: ${{ env.STEAM_APP_ID }}
            version: ${{ github.event.release.tag_name }}
