name: Build and Release Game

on:
  release:
    types: [published]

env:
  ITCH_GAME: ${{ vars.ITCH_GAME }}
  ITCH_USER: ${{ vars.ITCH_USER }}
  STEAM_APP_ID: ${{ vars.STEAM_APP_ID }}

jobs:
  build_game:
    name: Build Game
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Build
        uses: ./
        with: 
          version: ${{ github.event.release.tag_name }}
