name: Format GDScript

on:
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '.**'
      - 'LICENSE'
      - 'ACKNOWLEDGEMENTS'
      - '**.md'
      - '*.yml'
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths-ignore:
      - '.**'
      - 'LICENSE'
      - 'ACKNOWLEDGEMENTS'
      - '**.md'
      - '*.yml'

jobs:
  format_code:
    name: "Run Formatter"
    runs-on: ubuntu-latest
    # To prevent infinite loops
    if: "!contains(github.event.head_commit.message, 'Auto-Format GDScript')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - uses: actions/setup-python@v3
        with: 
          python-version: 3.x

      - run: pip3 install 'gdtoolkit==3.*'

      - run: gdformat **/*.gd

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-Format GDScript
          file_pattern: "**/*.gd"
